### ISSUE TITLE
Doesn't runs

### ISSUE THREAD

**Issue by Aaaaa-as** [mwbryant/bevy_space_game#2]
Compiles but does not run on Windows 10.
Says that there are no files (it is so) bevy_dylib-487d99b2c7b12540.dll and std-d7a86f21fcd377c7.dll.

**Comment by Aaaaa-as** [comment]
Strangely enough, it fixed itself for some reason.

**Comment by mwbryant** [comment]
Probably removing the dynamic linking flag will make this more consistent, I think it improved in modern bevy versions
